slack:
  webhook_url: <add your slack WEBHOOK URL here. required to send messages to slack>  
  channel: <add channel to send messages to>
  username: "water-cooler-bot"
  icon_emoji: ":water-cooler:"
zoom:
  api_key: <add zoom API KEY here>
  api_secret: <add zoom API SECRET here>
scheduling:
  # enter timezone used for computing weekdays and hours
  # must be from this list - https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # e.g. India - Asia/Kolkata, San Francisco - US/Pacific (or America/Los_Angeles)
  local_timezone: 'Asia/Kolkata'
  # days of the week during which this could get triggered 
  # mapping - M: 1, Tu:2, W:3, Th:4, F:5, Sat:6, Sun:7 
  working_days: [ 1, 2, 3, 4 ]
  # hours between which slack message could get triggered
  # e.g. 11:30 AM - 1 PM, 3 PM - 6 PM
  working_hours:
    - start: 11.5
      end: 13
    - start: 15
      end: 18
